camera_matrix:
- - 1053.1919510759649
  - 0.0
  - 491.5458179094769
- - 0.0
  - 2003.0591298396362
  - 514.89465920025
- - 0.0
  - 0.0
  - 1.0
distortion_coeffs:
- - -1.217975134921327
  - 1.4271619473108792
  - 0.004264267972709468
  - 0.021529756182672617
  - -0.9784510059237591
image_height: 1024
image_width: 1024
mean_reprojection_error: 0.22177211078325476
rms_error: 2.4744479410150375
